fragment MessageFields on Message {
  ... on UserMessage {
    id
    text
    gameUser {
      ...GameUserFields
    }
    timestamp
  }

  ... on RollMessage {
    id
    result {
      results {
        dice
        result
      }
      sum
    }
    gameUser {
      ...GameUserFields
    }
    timestamp
  }
}
